# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: UnitTest with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set CREDENTIALS
        run: echo ${{ secrets.CREDENTIALS}} > github.properties
      - name: JVM Test with Gradle
        run: ./gradlew jvmTest
      - name: JS Test with Gradle
        run: ./gradlew jsTest
      - name: Native Test with Gradle
        run: ./gradlew nativeTest
