# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: UnitTest with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Build Cache
        id: build-cache
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: JVM Test with Gradle
        run: ./gradlew jvmTest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: JS Test with Gradle
        run: ./gradlew jsTest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Native Test with Gradle
        run: ./gradlew nativeTest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
